<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>vda5050_master_ros2</name>
  <version>0.0.0</version>
  <description>ROS 2 service + publisher facade for VDA5050 master</description>
  <maintainer email="saurabh_kamat@a-star.edu.sg">Saurabh Kamat</maintainer>
  <maintainer email="lim_yew_hao@a-star.edu.sg">Yew Hao Lim</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <build_depend>nlohmann-json-dev</build_depend>

  <depend>builtin_interfaces</depend>
  <depend>rclcpp</depend>
  <depend>ament_index_cpp</depend>
  <depend>fmt</depend>
  <depend>libpaho-mqtt-dev</depend>
  <depend>libpaho-mqttpp-dev</depend>
  <depend>vda5050_core</depend>
  <depend>vda5050_interfaces</depend>

  <exec_depend>rosidl_default_runtime</exec_depend>
  <exec_depend>rmw_cyclonedds_cpp</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <test_depend>ament_cmake_gmock</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
